name: Build and Deploy to Netlify

on:
  push: # mainブランチへのpushトリガーを有効に戻す
    branches:
      - main
  repository_dispatch: # 外部イベントを受け取るトリガー
    types: [microcms_update] # microCMSからのWebhookで指定するevent_type

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GATSBY_MICROCMS_API_KEY: ${{ secrets.GATSBY_MICROCMS_API_KEY }}
      GATSBY_MICROCMS_SERVICE_ID: ${{ secrets.GATSBY_MICROCMS_SERVICE_ID }}

    steps:
      # 1. コードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. ファイル一覧を表示
      - name: List files
        run: ls -R

      # 3. Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 4. 依存関係をインストール
      - name: Install dependencies
        run: npm install

      # 5. Gatsby をビルド
      - name: Build Gatsby site
        run: npm run build

      # 6. Netlify CLI をインストール
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # 7. Netlify にデプロイ
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --dir=public --prod --site=$NETLIFY_SITE_ID
